import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import './globals.css';

import Providers from './providers';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={cn('font-sans', GeistSans.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
